name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push 이벤트 발생 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ruby 및 Jekyll 환경 설정
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # 사용하는 Ruby 버전 설정
          bundler-cache: true

      # 3. Jekyll 의존성 설치
      - name: Install Jekyll dependencies
        run: bundle install

      # 4. Jekyll로 사이트 빌드
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # 5. 빌드된 파일을 gh-pages 브랜치에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 인증 토큰
          publish_dir: ./_site
